bases:
  - ../kustomize
namePrefix: dev-
namespace: dev
commonLabels:
  environment: development

patches:
  - target:
      kind: Ingress
      name: resume-ingress
    path: ing-patch.yaml

images:
  - name: wgleich/resume
    newName: wgleich/resume
    newTag: "latest"

patchesStrategicMerge:
  - replicas.yaml
